language: node_js
env:
  - LIBGADU_VERSION="1.12.1"
node_js:
  - 6.9
addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    # install toolchains
    - gcc-5
    - g++-5
    - clang-3.6
before_install:
  - "pushd $PWD"
  - "cd /tmp"
  - "wget http://github.com/wojtekka/libgadu/releases/download/$LIBGADU_VERSION/libgadu-$LIBGADU_VERSION.tar.gz"
  - "tar -zxvf libgadu-$LIBGADU_VERSION.tar.gz"
  - "cd libgadu-$LIBGADU_VERSION"
  - "./configure --prefix=/usr"
  - "make"
  - "sudo make install"
  - "popd"
