language: node_js
env:
  - CXX=g++-4.8
node_js:
  - 6.9
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
before_install:
  - "sudo apt-get install"
  - "pushd $PWD"
  - "cd /tmp"
  - "wget http://github.com/wojtekka/libgadu/releases/download/1.12.1/libgadu-1.12.1.tar.gz"
  - "tar -zxvf libgadu-$LIBGADU_VERSION.tar.gz"
  - "cd libgadu-$LIBGADU_VERSION"
  - "./configure --prefix=/usr"
  - "make"
  - "sudo make install"
  - "popd"
