language: node_js
env:
  - LIBGADU_VERSION="1.12.1"
node_js:
  - 6.9
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - "pushd $PWD"
  - "cd /tmp"
  - "wget http://github.com/wojtekka/libgadu/releases/download/$LIBGADU_VERSION/libgadu-$LIBGADU_VERSION.tar.gz"
  - "tar -zxvf libgadu-$LIBGADU_VERSION.tar.gz"
  - "cd libgadu-$LIBGADU_VERSION"
  - "./configure --prefix=/usr"
  - "make"
  - "sudo make install"
  - "popd"
